version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: '1gb'
    depends_on :
      - hub
    environment: 
      - HUB_HOST=hub  
  firefox:
    image : selenium/node-firefox:3.141.59
    depends_on :
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: asuhail8/sel-doc
    depends_on :
      - chrome
      - firefox
    environment :
      - BROWSER=chrome
      - HUB_HOST=hub  
      - MODULE=search-module.xml
    volumes:
      - D:/AbdullaSuhail/selenium-docker/docker-selenium/output/search-result:/usr/share/udemy/test-output
  book-flight-module:
    image: asuhail8/sel-doc
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - D:/AbdullaSuhail/selenium-docker/docker-selenium/output/book-result:/usr/share/udemy/test-output
      